### ISSUE TITLE
Can you implement links?

### ISSUE THREAD

**Issue by iloveclover** [miku-nyan/Overchan-Android#10]
Whenever someone posts a link to a site, you can't do anything but read it. Please add the feature to open links.

Also, can you add a way to multi-quote many people at once?

Also, can you add a way to post webms through the gallery?

Also, can you find a way to stop 4chan from saying "Sending a Post" and "Failed to send" before I even get to the final part of the captcha?

Also, can you add some type of notification if someone replies to you and add (You) to someone quoting you?

**Comment by miku-nyan** [comment]
> Please add the feature to open links.

It works correctly (the link must be inside of "<a>" tag, otherwise it's the regular text).

> multi-quote many people at once

What do you mean? You can add the quotes one by one (add one, then return to the thread, then add one more, etc.)

> notification if someone replies to you and add (You) to someone quoting you

On most of the imageboards it's hard (or impossible) to determine your posts exactly.

**Comment by BoBeR182** [comment]
No one on imageboards types "<a>" Using regex or similar for anything that starts with httpXXXXXXXXX.XXX should be sufficient to turn into a link.

**Comment by PwnicornDev** [comment]
[Linkify](https://developer.android.com/reference/android/text/util/Linkify.html) could be used to make links clickable:

``` Java
Linkify.addLinks(someView, Linkify.WEB_URLS);
```

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/b48488e81e6409fbfd5ff95991f4fbc0e9534dfb
