### ISSUE TITLE
App has trouble changing orientations on android 2.3.4

### ISSUE THREAD

**Issue by derram** [miku-nyan/Overchan-Android#12]
When I try to switch from portrait to landscape, the app drops to the homescreen and tries to resume repeatedly. This behavior happens every time I switch orientations, but it has only crashed completely once. For the most part, it just has to retry the orientation change 6 or 7 times before it sticks.

**Comment by miku-nyan** [comment]
I can't find your crash report. Have you sent it?
Also I myself use Android 2.3.4 and can't reproduce this. The activity is finishing, then starts again in a second (that's because the method `Activity.recreate()` was added in Android 3.0 Honeycomb)

**Comment by derram** [comment]
Not sure where to find the crashlog, though it's only crashed once.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/58f110d9feb891d9ee5d0f254643eb7c58f130a3

**Comment by derram** [comment]
Working great, thanks!
