### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by Udinanon** [miku-nyan/Overchan-Android#13]
we need support for more captchas, like 8chan's

**Comment by miku-nyan** [comment]
What's the problem with the captcha on 8chan? (it only appears when you are using tor/onion)

**Comment by Udinanon** [comment]
in some sections captchas are active and you can not post without filling them, but the app doesn't support them so posting is impossible from the app and you have to open the browser

**Comment by miku-nyan** [comment]
I've already seen, for example on /pol/ to create a new thread.
https://github.com/miku-nyan/Overchan-Android/commit/3cb7b1d22600cf762bda1f4e5aeb9d34059b1b1e

**Comment by Udinanon** [comment]
I hope it works also on /furry/ posts and for the new botnet check they are doing, as it needs to be refilled every day
