### ISSUE TITLE
Doesn't support Krautchan Komturcode

### ISSUE THREAD

**Issue by PwnicornDev** [miku-nyan/Overchan-Android#17]
A [Komturcode](http://krautchan.net/komturcode-en.html) is a code you can use to post on Krautchan if you are affected by a network ban. It is stored in a cookie, so it should be easy to implement.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/97385a439fc03cc12cc9724284726044d4b0df97

**Comment by PwnicornDev** [comment]
That was fast, thank you very much!
![gibe_herzen](https://cloud.githubusercontent.com/assets/3987812/8604921/e161d986-2681-11e5-80c5-7526f6aaf222.jpg)
