### ISSUE TITLE
reCaptcha 2.0

### ISSUE THREAD

**Issue by picco911** [miku-nyan/Overchan-Android#18]
на что дальше надо нажать ? 
это глюк или я кнопку не вижу.

![screenshot_2015-06-23-10-22-27](https://cloud.githubusercontent.com/assets/9295425/8300864/f8d0c3f4-1991-11e5-9c32-53dfb7c9204d.png)

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/e43089991d9a7b8ab3f41c8c8b880a09ff8fe308
