### ISSUE TITLE
А где gradle-скрипты находятся?

### ISSUE THREAD

**Issue by magicgoose** [miku-nyan/Overchan-Android#2]
Что-то не могу их найти.

**Comment by miku-nyan** [comment]
А нигде

**Comment by magicgoose** [comment]
Серьёзно?
Зачем так? Мы же в 2015 году, вроде ;D

**Comment by miku-nyan** [comment]
Ну и зачем этот тормозной монстр, когда Ant нормально собирает?

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/db6593c1ff18de009f45bfe84f54311829c2cd93
Вроде собирается и даже как-то работает, импортируется в андроид студию.
Только ndk как и был через жопу, не читает makefile, только теперь при сборке говорит "текущая поддержка ndk - deprecated, а нормальная будет когда-нибудь", лол.

**Comment by magicgoose** [comment]
а зачем NDK? только ради поддержки мёртвого формата GIF? может, и не нужно это?

**Comment by miku-nyan** [comment]
толстяк :3

**Comment by magicgoose** [comment]
Что толстого-то? WebM же есть уже, это лучше для анимации. Статичные гифки тем более не нужны, т.к. PNG.

**Comment by miku-nyan** [comment]
Ну так давай дальше, ещё IPv4 дропнем. Он тоже не нужен, IPv6 лучше.
И что, его 1,5 провайдера и 3,5 сайта поддерживают?

**Comment by magicgoose** [comment]
WebM поддерживается везде, в отличие от IPv6

**Comment by miku-nyan** [comment]
Во-первых, мочепараша и ещё несколько борд - не "везде".
А вот gif таки поддерживается везде, ИЧСХ, гифки почему-то постят и там, где поддерживается и webm (интересно, почему?).

**Comment by magicgoose** [comment]
Потому что синдром утёнка и типичное русское противление всему новому.

**Comment by miku-nyan** [comment]
Даже не будем говорить о том, что webm как формат видео форсится только гуглом, а де-факто стандарт пока mpeg4/h264, и не всё воспроизводит даже VP8. Для _анимации_ webm и вообще видео не всегда оптимально и зачастую оверхед, тогда уж за APNG, но как-то не сложилось.
Ещё и русских приплёл
http://boards.4chan.org/wsg/ http://boards.4chan.org/gif/
часть там вебмки, но всё остальное, видимо, русские постят.
Алсо, есть что по делу, или к чему этот разговор?

**Comment by magicgoose** [comment]
Не, просто потроллить зашёл, как всегда. :)
