### ISSUE TITLE
Feature Request: Colored ID's

### ISSUE THREAD

**Issue by ghost** [miku-nyan/Overchan-Android#21]
8chan's colored ID's are helpful when browsing boards such as /pol/ which have IDs enabled. The app called ouroboros, which is dedicated to 8chan, has implemented this feature. It would be a mild inconvenience if this feature was found in overchan as well.

Thank you for your time.

**Comment by ghost** [comment]
convenience\* lol
speech-to-text's fault

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/41092f610e0695cb6ff456620d3cc51a363363c4
