### ISSUE TITLE
Support JPEG EXIF rotation?

### ISSUE THREAD

**Issue by James-E-A** [miku-nyan/Overchan-Android#33]
Most smartphones use EXIF rotation to declare the orientation of photographs taken with them. Overchan does not support the EXIF rotation tags.

So if I select a picture off my phone with Overchan, and post it to a board, the image will likely appear sideways on the very device I took the picture with.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/9345bc7e86c0cf6da51a44f2d1b7fbe21b7328f3
