### ISSUE TITLE
Add support for 8ch flags

### ISSUE THREAD

**Issue by James-E-A** [miku-nyan/Overchan-Android#36]
8chan's board-level flags on boards such as [/tech/](https://8ch.net/tech/) aren't displayed.

The thread at [>>>/tech/334916](https://8ch.net/tech/res/334916.html#335013) is a pretty good example of these flags

**Comment by petrusd987** [comment]
:+1:

**Comment by miku-nyan** [comment]
closed as double of https://github.com/miku-nyan/Overchan-Android/issues/27
If it is not about this, please reopen.
