### ISSUE TITLE
Thread list sidebar options

### ISSUE THREAD

**Issue by Klaster1** [miku-nyan/Overchan-Android#38]
Please consider the following options for theards list sidebar:
1. Ability to choose the side it's shown at, left or right.
2. Add widths smaller than 25%, on large tablet screens even the narrowest one looks too wide.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/d09ef14dec22300916cca4195c71433dc835f988
https://github.com/miku-nyan/Overchan-Android/commit/778f874b586a82355b011c1033341d6044d00f24
