### ISSUE TITLE
8Chan 404 Error

### ISSUE THREAD

**Issue by Udinanon** [miku-nyan/Overchan-Android#46]
8CHan only gives a 404 Error to all boards , even after cache deletion and reset
Only change was installation of AdAway

**Comment by miku-nyan** [comment]
settings.php?board=xxx (information about board) somehow returns 404

dirty fix: https://github.com/miku-nyan/Overchan-Android/commit/bf233360556d09ffb1f692cea9e813770c69c74e

**Comment by ctrlcctrlv** [comment]
Hello, sorry for the inconvenience. 

`settings.php` had a bug, so I quarantined it by moving it elsewhere to fix it and have now put it back.
