### ISSUE TITLE
Option to share threads via mail etc (using "Share" dialogue)

### ISSUE THREAD

**Issue by ghost** [miku-nyan/Overchan-Android#48]
Hello,

At the moment, the only way to share thread with a friend is to open desired thread in browser and use its option to share pages.

So i propose 2 things:
- add "share" button in menu when we long press thread title (in threads list);
- add "share" button in thread menu (when we already open threads to check for its content).

p.s. By "Share" i mean to invoke that android dialogue where there are possible apps which are registered to do some share actions.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/946b6715ee0038ff925dc76e5ae4c3526fb2323a
There's already too many elements in menu, I add it to the context-menu of the tab.

**Comment by ghost** [comment]
Great, thank you for quick response and new feature.
