### ISSUE TITLE
Remove honeychan.net

### ISSUE THREAD

**Issue by keiranrowan** [miku-nyan/Overchan-Android#50]
honeychan.net is no longer running due to the underwhelming amount of traffic and overwhelming costs.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/d73ef56d28377347440fa93e89ab021cc7933116

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/d73ef56d28377347440fa93e89ab021cc7933116
