### ISSUE TITLE
/unnecessary/ orientation change handler

### ISSUE THREAD

**Issue by luk1337** [miku-nyan/Overchan-Android#55]
Can I ask why we do this https://github.com/miku-nyan/Overchan-Android/blob/master/src/nya/miku/wishmaster/ui/MainActivity.java#L488 afaik it only causes threads to get refreshed on orientation change which /shouldn't/ be the thing we want.

**Comment by miku-nyan** [comment]
That's because when screen width is changed, text floating (around thumbnails) may be broken.

> causes threads to get refreshed

No

**Comment by luk1337** [comment]
Yeah, you're right. Threads aren't being refreshed but expanded posts are just being collapsed.
