### ISSUE TITLE
(KEBAB HAS BEEN REMOVED FROM PREMISES)

### ISSUE THREAD

**Issue by Klaster1** [miku-nyan/Overchan-Android#57]
Currently the KC ban message has same color as plain text, while it should be red.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/28f8c7beb8e0507b13a359467fb2712e7f992ab1

**Comment by Klaster1** [comment]
Did you test it? I still see plain text color ban messages on /int/.

**Comment by hey-red** [comment]
Link?

**Comment by Klaster1** [comment]
Disregard that and sorry for the false alarm, I had dev build installed,
which obviously doesn't autoupdate.

2016-01-06 13:57 GMT+07:00 Ke Ke notifications@github.com:
