### ISSUE TITLE
javax.net.ssl.SSLException: SSL handshake aborted

### ISSUE THREAD

**Issue by Kalaver** [miku-nyan/Overchan-Android#6]
При вызове метода getFromUrl() класса nya.miku.wishmaster.http.streamer.HttpStreamer возникает ошибка вида: "javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x6e008030: I/O error during system call, Connection reset by peer", если запросить страницу с сервера https://n0l.ch/ , который при соединении использует  TSL 1.2

**Comment by miku-nyan** [comment]
Ну, дело не тут не в классе HttpStreamer и вообще не в HTTP-клиенте (apache-hc).
Вот этот код бросает такое же исключение:

``` java
URL url = new URL("https://n0l.ch/b");
HttpURLConnection con = (HttpURLConnection) url.openConnection();
ByteArrayOutputStream buf = new ByteArrayOutputStream();
IOUtils.copyStream(con.getInputStream(), buf);
System.out.println(buf.toString("UTF-8"));
con.disconnect();
```

Причём, на Android 5.0 исключения нет, страница грузится.

По поводу TLS: на 2-chru.net как раз разрешён только TLS 1.2, и там https работает нормально, начиная с Android 4.3. (на более ранних версиях можно заходить через tor)
Так что здесь дело в чём-то ещё.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/18c3f47d1e6d56a32e33db39235c9de57c281fd2

С использованием gms провайдера всё работает, начиная с Android 2.3 (если установлены google apps).
Для эмулятора из sdk нужно выбирать образ системы не просто, например, Android 4.4.2 - API Level 19, а Google APIs - API Level 19, и в эмуляторе это работает только начиная с 4.2
