### ISSUE TITLE
List of imageboards is gone since 1.3.4

### ISSUE THREAD

**Issue by ghost** [miku-nyan/Overchan-Android#60]
Before 1.3.4 you could see the list of imageboards and easily go to one of them. It looked like that ;

![screenshot_2015-11-22-10-46-46](https://cloud.githubusercontent.com/assets/7694864/11323047/bada431c-9106-11e5-9f2d-25d606df1512.png)

But now the list is gone and it looked like that :

![screenshot_2015-11-22-10-47-38](https://cloud.githubusercontent.com/assets/7694864/11323051/c8c299c0-9106-11e5-818a-cb706ef3e12d.png)

Is it normal ?

**Comment by nanomader** [comment]
Yes, its normal. Option to show imageboard list is in Preferences. Just press menu button on your phone, select Prerefences and touch second option below Advanced label.
![screenshot_2015-11-22-13-22-51](https://cloud.githubusercontent.com/assets/7474972/11323772/bfe79c16-9114-11e5-9758-d273797ed054.png)

**Comment by ghost** [comment]
My bad, I've missed it. Thanks

**Comment by miku-nyan** [comment]
You can also add your favourite chans and boards to "quick access" list on the new tab page.
The option to show imageboard list is available in non-google-play version.

**Comment by ghost** [comment]
Yeah but I was aware of that functionality, I just though that this disappearing was a bug.

Great app by the way :)
