### ISSUE TITLE
Ability to add themes from XML files?

### ISSUE THREAD

**Issue by PwnicornDev** [miku-nyan/Overchan-Android#65]
I wanted to make my own theme, but I'd have to compile the app just for the theme. Would it be possible to load themes maybe from a specified folder or such?

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/57961a4b044d1dfb4ef9727d31ed97f054d823ec
https://github.com/miku-nyan/Overchan-Android/commit/6c56e42638a0955f5ccc204de15ad00972cbce43

**Comment by miku-nyan** [comment]
Custom theme is JSON file.
Example (values from Neutron theme):

```
{
  "baseTheme": "dark",
  "materialPrimary": "#212121",
  "materialPrimaryDark": "#000000",
  "materialNavigationBar": "#000000",
  "textColorPrimary": "#698CC0",
  "activityRootBackground": "#212121",
  "sidebarBackground": "#CC212121",
  "sidebarSelectedItem": "#6E6EA5",
  "listSeparatorBackground": "#191919",
  "postUnreadOverlay": "#7F7F3F3F",
  "postBackground": "#2C2C2C",
  "postForeground": "#698CC0",
  "postIndexForeground": "#789922",
  "postIndexOverBumpLimit": "#C41E3A",
  "postNumberForeground": "#C9BE89",
  "postNameForeground": "#B4B9CD",
  "postOpForeground": "#008000",
  "postSageForeground": "#993333",
  "postTripForeground": "#228854",
  "postTitleForeground": "#3941AC",
  "postQuoteForeground": "#789922",
  "spoilerForeground": "#48B0FD",
  "spoilerBackground": "#575757",
  "urlLinkForeground": "#C9BE89",
  "itemInfoForeground": "#999999",
  "searchHighlightBackground": "#EF0FFF"
}
```

Key "baseTheme" defines the base (system) theme, valid values: "dark", "light".
All other keys are optional (if not defined, default values from Neutron or Futaba will be used), define colors.
![themes](https://cloud.githubusercontent.com/assets/8571961/11703024/a91632e6-9eec-11e5-86cf-513ff7dc5bce.png)

The result file should have ".json" extension (to be visible in file dialog).
