### ISSUE TITLE
Video channels swapped in Android 5.0.1 on KC

### ISSUE THREAD

**Issue by Klaster1** [miku-nyan/Overchan-Android#66]
What title says, it seems that video channels are swapped when watching webm's on /int/, so red becomes blue. YouTube and Firefox don't have this issue.

**Comment by miku-nyan** [comment]
I can't reproduce this on emulator. Example of webm?
Anyway I believe this is an issue of android (built-in VideoView). You can switch to the external video player in preferences.

**Comment by Klaster1** [comment]
This indeed turned out to be a VideoView issue, too bad there's no way to
fiddle with it's settings. Where exactly I can switch the player?

**Comment by miku-nyan** [comment]
Preferences -> (Appearance) -> Gallery -> Built-in video player

**Comment by Klaster1** [comment]
Sorry for the late answer, external player works fine.
