### ISSUE TITLE
Overchan keeps crashing - stuck on "page 4" of a chan

### ISSUE THREAD

**Issue by Drachlox** [miku-nyan/Overchan-Android#68]
Last time i used the app, i was browsing one of the chan's and was on page 4 on that chan.
Now, when opening Overchan, it continues to try to load page 4 but are unable to do so. Any action on my part, like going back to page 3 or "x"-ing out the "open" pages, or basically just hitting the screen anywhere makes overchan "stop working". 

In its current state, i am unable to use the app. 

Do i have to reset the entire app by uninstall/reinstall or do i have to wait for an update? 

(i realize its in the middle of christmas/newyear, so i don't expect a solution any time soon. Just thought i'd mention the issue.) :+1:

**Comment by miku-nyan** [comment]
What Android version and version of application?
Did you send the crash report?

**Comment by miku-nyan** [comment]
SD-card (storage) works fine? (and its file system)

**Comment by Drachlox** [comment]
Android 4.3
Latest version of app (have checked F-droid and there is no newer version available)
Send crash report? How? When it crash all it says is "Overchan has stopped" and gives me an "OK" button.

**Comment by miku-nyan** [comment]
It seems that ACRA (crash reporting) is broken in last version (1.3.11).
Can you send me logcat messages which appear during crash? (using adb logcat or application like [this](https://f-droid.org/repository/browse/?fdid=rs.pedjaapps.alogcatroot.app))

**Comment by miku-nyan** [comment]
Version 1.3.12 with fixed ACRA is built and now available on [f-droid](https://f-droid.org/repository/browse/?fdfilter=overchan&fdid=nya.miku.wishmaster).
Please update and send the crash report. (then tell me approximate time)

**Comment by Drachlox** [comment]
Seems the update somehow tweaked whatever was wrong. It seems to be ok so
far. :)

On Mon, Dec 28, 2015 at 6:50 PM, Miku Hatsune notifications@github.com
wrote:

> Version 1.3.12 with fixed ACRA is built and now available on f-droid
> https://f-droid.org/repository/browse/?fdfilter=overchan&fdid=nya.miku.wishmaster
> .
> Please update and send the crash report. (then tell me approximate time)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/miku-nyan/Overchan-Android/issues/68#issuecomment-167612406
> .

## 

Thomas Bakke

**Comment by miku-nyan** [comment]
It's weird, nothing else was changed in the application (only ACRA).
