### ISSUE TITLE
Cannot create directory error 

### ISSUE THREAD

**Issue by ghost** [miku-nyan/Overchan-Android#75]
I just freshly installed onto a Nexus 6 phone and kept getting this error while trying to download images from both 4chan and 8ch boards:

http://imgur.com/Pipc3XU

**Comment by miku-nyan** [comment]
Check the downloads directory path in preferences. Is it correct?

**Comment by ghost** [comment]
Hello,

I just figured it out.

For some reason, the system isn't asking for storage permissions when the
app is being installed.

**Comment by miku-nyan** [comment]
The similar problem (permissions) was in early Marshmallow (Android 6) images and emulator.
Please confirm, is it still exists?

**Comment by tidux** [comment]
Confirmed on fully up to date Android 6.x (Pixel C, stock firmware) today.  Path is set to default OS-wide download directory, which exists, but it's getting a can't create directory error without prompting for SD card access.
