### ISSUE TITLE
Channels requiring "cloudflare authentication"

### ISSUE THREAD

**Issue by Drachlox** [miku-nyan/Overchan-Android#78]
It seems something is wrong when it comes to channels requiring you to authenticate trough "cloudflare". 
The way this comes up is when trying to access the channel, a popup appears where it asks you to enter the number from the image it shows you. When you do and press the button to submit it, it just opens up another window. 

This type of authentication has worked in the past trough OverChan, and the authentication seems to work as intended when visiting the chan trough a browser, so i suspect the issue is with the app not sending the user input correctly, resulting in it opening another window. 

A chan where this happens: 2ch.hk

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/dd8e7ed272c82b47625ed9f34cdbaade550058b2
