### ISSUE TITLE
Saved images not added to Android Media Index

### ISSUE THREAD

**Issue by James-E-A** [miku-nyan/Overchan-Android#81]
Images saved via Overchan are not automatically added to whatever registry Android uses to keep track of media. This creates a situation like [this person's](https://android.stackexchange.com/questions/8526/force-media-update), except for images.

The images simply don't appear in the Gallery until the device is power-cycled.

What I usually have to do is every time I finish an Overchan session, pull up an app that allows me to manually rescan a folder (I've been using [FX](http://android.nextapp.com/site/fx) for this), navigate to the Downloads folder, and rescan it.  
This behavior should not be necessary. Overchan should automatically update the Android Media Index upon successful download of a file.

**Comment by kogoromori** [comment]
same here...
actually i can access them via filemanager

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/763b8b9214b8f546ac04552139205e772198f1cf

**Comment by James-E-A** [comment]
Hmm, it would probably be really good PR if you replied to [this review](https://play.google.com/store/apps/details?id=nya.miku.overchan&reviewId=Z3A6QU9xcFRPSGwyd2V2VHBhWkQyeG5XMVRSSHBjQnV4WnFpUGdjMDVKZmtJbVZEOUtPNGh1R19fSUItemczbzlzSjJmR2x1QVhScE5kZ1kxVjRKUnY2Snc&hl=en):

> I'm comparing this review to the Clover app. I only faced a couple issues. The 2 being that my downloaded pictures would not show up in my gallery, after Googling I could not find a real fix. Also when scrolling threw the images, the thread would not scroll with it. But besides thoses two things, it's a great app. Took ME a little to get used to. 7/10 app, would be 10/10 with thoses problems fixed

With something along the lines of

> We fixed the not-showing-up-in-gallery issue, the next version will have this fixed.
> If you want the thread to scroll with images, go to Settings, Gallery, and check "Scroll to attachments".

It's one of the top reviews that shows up (and among the only legitimate negative reviews), and to have an Official Developer Reply announcing that everything he brought up is fixed would make Overchan look really good to those still looking for a chan app.

**Comment by miku-nyan** [comment]
JamesTheAwesomeDude,
ok, thank you

**Comment by James-E-A** [comment]
Issue is still affecting me with Overchan 1.3.13 on Android 5.1.1

**Comment by miku-nyan** [comment]
small mistake
https://github.com/miku-nyan/Overchan-Android/commit/0a7ec8ac428f030ef3cbfafe2a970464d1d5819a
