### ISSUE TITLE
Update boardlists...

### ISSUE THREAD

**Issue by mariokamenjak** [miku-nyan/Overchan-Android#82]
You need to update the boardlists. On some chans that I visit , you have many 404 subboards, and some new subboards are not there.

**Comment by miku-nyan** [comment]
I can not check every chan forever and synchronize boardlists, please report more concretely for each chan.

**Comment by mariokamenjak** [comment]
Oh sorry, I forgot to mention, I meant Lainchan. I visit that one often.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/a93492cbf0a5eeb82ab1fc275373bada7f13a749
