### ISSUE TITLE
7chan limited to 1000 posts per thread

### ISSUE THREAD

**Issue by charlyzard** [miku-nyan/Overchan-Android#84]
On some big threads, overchan seems to only show the first 1000 posts. I think it's because overchan is not using the correct link.

For example, overchan is using this link:

https://7chan.org/tg/res/98039.html

that only shows 1000 posts.

By browsing with an external web browser, the corerct link to browse the entire thread is (at the time of writing this issue):

https://7chan.org/read.php?b=tg&t=98039&p=p1-4035

which shows 4035 posts

**Comment by miku-nyan** [comment]
75a1946ccf63676460ae8378a6d9c17eb68ad099 ajax.php returns all posts
