### ISSUE TITLE
The Captchas

### ISSUE THREAD

**Issue by iloveclover** [miku-nyan/Overchan-Android#9]
Hello. I have an issue with the captchas on regular 4chan. They always show up as the longest captchas available, and it is extremely difficult to post.

Other than that, amazing app, one of the best I've ever used.

**Comment by miku-nyan** [comment]
Hello. Are you using Recaptcha 2? (Preferences → Imageboards → 4chan)

**Comment by iloveclover** [comment]
Oh, I did not see that option. Thanks so much! I'll definitely recommend this app.

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/d4fe23b7ce5c8b817c4952f9578986df24a45eaa
